version: '3.9'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "1217:1217"
    deploy:
      mode: replicated
      replicas: 1

  # API Service
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - TZ=Asia/Taipei
      - PORT=8080
      - AuthApiUrl=http://authentication-service:8080/Authentication
    volumes:
      - ./broker-service:/app

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - TZ=Asia/Taipei
      - PORT=8080
      - postgresDB=postgresql://postgres:password@postgres-db/users
      - LoggerApiUrl=http://logger-service:8080/WriteLog
    volumes:
      - ./authentication-service:/app
    depends_on:
      - postgres-db

  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - TZ=Asia/Taipei
      - PORT=8080
      - mongoDB=mongodb://mongo:password@mongo-db:27017
    volumes:
      - ./logger-service:/app
      - log-data:/logs
    depends_on:
      - mongo-db

  # DB
  postgres-db:
    image: 'postgres:14.2'
    ports:
      - "5435:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo-db:
    image: mongo:8.0.10
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  # ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Taipei
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 80
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.3
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - log-data:/app/logs:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

volumes:
  log-data:
  esdata: