version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - PORT=8080
      - AuthApiUrl=http://authentication-service:8080/Authentication
    volumes:
      - ./broker-service:/app

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - PORT=8080
      - postgresDB=postgresql://postgres:password@postgres-db/users
    volumes:
      - ./authentication-service:/app

  postgres-db:
    image: 'postgres:14.2'
    ports:
      - "5435:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/